env variables & kitty config

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,4 +1,5 @@
 #!/bin/bash
+base=$(readlink -f "$(dirname $(readlink -f "$0"))/..")
 if [[ "$EUID" == 0 ]]; then
     echo "This should not be run as root!"
     exit 1
@@ -9,6 +10,19 @@ if ! command -v ansible > /dev/null; then
     if cat /etc/os-release | grep ID=arch > /dev/null; then
         sudo pacman -Sy ansible
     fi
+fi
+
+if ! command -v ansible > /dev/null; then
+    echo "Asible couldn't be installed."
+    exit 1
+fi
+
+if ! command -v python3 > /dev/null; then
+    echo "Python 3 is required (should come with Ansible anyway)."
+    exit 1
+fi
+if ! "$base/bin/prepare" 1>/dev/null; then
+    exit 1
 fi
 
 ansible-galaxy collection install -r ansible/requirements.yml
